# Setup
title: suntdoar.eu
url: https://suntdoar.eu
baseurl: ""
permalink: pretty
email: extremqcontact@gmail.com
youtube: https://www.youtube.com/@Extremq
github: https://github.com/extremq

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Markdown options
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  input: GFM
# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: "G-EL1EQ30NQ9"


# Specify the author for blog posts
author:
  name: Extremq
  url: https://github.com/extremq
  email: extremqcontact@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /

  - title: About
    url: /about